"""added test migration

Revision ID: 7997cd8298fa
Revises: a56fa0989d32
Create Date: 2025-01-15 21:01:51.432247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7997cd8298fa'
down_revision = 'a56fa0989d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_migration', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.drop_column('test_migration')

    # ### end Alembic commands ###
